services:
  - type: web
    name: emotion-analysis-app
    env: python
    python_version: "3.11.5"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production