services:
  - type: web
    name: emotion-analysis-app
    env: python
    preDeployCommand: "pip install --upgrade pip && pip install poetry==1.5.1"
    buildCommand: "poetry config virtualenvs.in-project true && poetry install"
    startCommand: "poetry run gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: FLASK_ENV
        value: production